
/**
 * Created by PhpStorm.
 * User: triest
 * Date: 25.01.2018
 * Time: 21:29
 */
<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')
        ->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Стили -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Скрипты -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ->prependFile($this->basePath('js/tinymce/tinymce.min.js'))
    ?>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="<?= $this->url('posts') ?>">Home2</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?= $this->content; ?>
    <hr>
    <footer>
        <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd.
            All rights reserved.
        </p>
    </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
