<?php
/**
 * Created by PhpStorm.
 * User: triest
 * Date: 05.01.2018
 * Time: 14:02
 */

$title = 'Delete post';
$url   = $this->url('post', ['action' => 'delete', 'id' => $id]);
$url2   = $this->url('post', ['action' => 'index', 'id' => $id]);
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Вы уверены, что хотите удалить пост
    "<?= $this->escapeHtml($post->title) ?>"
 ?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $post->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>
<a href="<?= $this->url('post', ['action' => 'index']) ?>">Главная</a>
