<?php
// module/Post/view/post/post/edit.phtml:

$title = 'Edit post';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>

<?php

$post = $form->get('title');
$post->setAttribute('class', 'form-control');
$post->setAttribute('placeholder', 'Post title');


$post2 = $form->get('text');
$post2->setAttribute('class', 'form-control');
$post2->setAttribute('placeholder', 'Post');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
$url   = $this->url('post', ['action' => 'delete', 'id' => $id]);
$form->setAttribute('action', $this->url('post', [
    'action' => 'edit',
    'id'     => $id,
]));



$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($post) ?>
    <?= $this->formElement($post) ?>
    <?= $this->formElementErrors()->render($post, ['class' => 'help-block']) ?>
</div>
    <div class="form-group">
        <?= $this->formLabel($post2) ?>
        <?= $this->formElement($post2) ?>
        <?= $this->formElementErrors()->render($post2, ['class' => 'help-block']) ?>
    </div>



<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
<div class="form-group">
        <a href="<?= $this->url('post', ['action' => 'index']) ?>">Главная</a>
    </div>