<?php



$this->headTitle($post->title);
$form = $this->form;
$form->get('author')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Author\'s name'
]);
$form->get('comment')->setAttributes([
    'class'=>'form-control',
    'rows'=>6,
    'placeholder'=>'Text'
]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->setAttribute('action', $this->url('post', ['action' => 'addcomment']));
$form->prepare();
$form->prepare();
?>



<a href="
    <?= $this->url('application', ['action'=>'index']); ?>">

</a>



<hr>

<a name="comment"></a>
<h3><b><?= $this->escapeHtml($post->title) ?></b></h3>

<div class="row">
    <div class="col-md-8">
        <br>
        <?= $this->escapeHtml($post->text) ?>
    </div>

</div>
<br>
<a href="<?= $this->url('post', ['action' => 'delete', 'id' => $post->id]) ?>">Delete</a><br>
<a href="<?= $this->url('post', ['action' => 'edit', 'id' => $post->id]) ?>">Edit</a><br>
<br>
<a class="btn btn-primary  active" href="<?= $this->url('post', ['action' => 'index']) ?>" role="button">К списку статей </a>
<br><br><br>
Комментарии:

<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<?= $this->form()->openTag($form); ?>

<div class="form-group">
    <?= $this->formLabel($form->get('author')); ?>
    <?= $this->formElement($form->get('author')); ?>
    <?= $this->formElementErrors($form->get('author')); ?>
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('comment')); ?>
    <br>
    <?= $this->formElement($form->get('comment')); ?>
    <?= $this->formElementErrors($form->get('comment')); ?>
    <?= $this->formElementErrors($form->get('comment')); ?>
    <br>
    <?= $this->formElement($form->get('submit')); ?>
</div>
